name: Test Clawpack on MacOS 14 Python 3.10 Numpy 1.25

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

  workflow_dispatch:

permissions:
  contents: read

env:
  CLAW: ${{ github.workspace }}

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

     - name: Install dependencies
      run: |
        brew update
        brew reinstall gfortran 
        python -m pip install --upgrade pip
        pip install numpy==1.25
        pip install flake8 meson-python ninja pytest
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Checkout Clawpack
      uses: actions/checkout@v4.1.5
      with:
        repository: clawpack/clawpack
        submodules: true

    - name: Install clawpack
      run: |
        pip install --no-build-isolation --editable .