name: Test Editable Clawpack on Ubuntu 22.04 Python 3.9 Numpy 1.24

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

  workflow_dispatch:

permissions:
  contents: read

env:
  CLAW: ${{ github.workspace }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
    - name: Install numpy
      run: |
        #Force gfortran reinstallation in Ubuntu
        sudo apt-get update
        sudo apt-get install -y gfortran
        python -m pip install --upgrade pip
        pip install numpy==1.24
        pip install flake8 meson-python ninja pytest
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Checkout Clawpack
      uses: actions/checkout@v4.1.5
      with:
        repository: clawpack/clawpack
        submodules: true

    - name: Install clawpack
      run: |
        pip install --no-build-isolation --editable .