name: Test Clawpack on MacOS 14 Python 3.11 Numpy 1.24

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

  workflow_dispatch:

permissions:
  contents: read

env:
  CLAW: ${{ github.workspace }}

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        #Force gfortran reinstallation
        brew update
        brew reinstall gfortran      

        python -m pip install --upgrade pip
        pip install numpy==1.24
        pip install  meson-python ninja
    - name: See setup
      run: |
        echo "System architecture: $(uname -m)"
        python --version
        echo -n "Numpy version: " && python -c "import numpy; print(numpy.__version__)"
    - name: Install clawpack
      run: |
        pip install clawpack