name: Test Clawpack CI

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

  workflow_dispatch:

permissions:
  contents: read

env:
  CLAW: ${{ github.workspace }}

jobs:
  build:
    runs-on: macos-latest
    continue-on-error: true
    steps:

    - name: Install Brew and pyenv
      run: |
        brew update
        brew install pyenv
        brew install pyenv-virtualenv

    - name: Test Clawpack
      run: |
        python_versions=(3.8 3.10 3.12)
        numpy_versions=(1.24 1.26 2.0)
        touch testing_pip_clawpack.log
        echo "Mac OS 14" > testing_pip_clawpack.log
        echo "Architecture: $(uname -m)" >> testing_pip_clawpack.log

        for python_version in ${python_versions[@]}; do
            for numpy_version in ${numpy_versions[@]}; do
                echo "Error installing Python..." > error_py${python_version}_np${numpy_version}.log
                pyenv install $python_version 2>> error_py${python_version}_np${numpy_version}.log

                echo "Error setting Python version..."  >> error_py${python_version}_np${numpy_version}.log
                python -m pip install --upgrade pip 2>> error_py${python_version}_np${numpy_version}.log
                pyenv global $python_version 2>> error_py${python_version}_np${numpy_version}.log

                echo "Error installing Numpy..."  >> error_py${python_version}_np${numpy_version}.log
                pip install numpy==$numpy_version

                echo "Error installing Clawpack..."  >> error_py${python_version}_np${numpy_version}.log
                pip install clawpack

                full_python_version=$(python --version)
                full_numpy_version="Numpy $(python -c 'import numpy; print(numpy.__version__)')"
                
                if python -c "import clawpack";then
                    echo "${full_python_version}, ${full_numpy_version}: Passed" >> testing_pip_clawpack.log
                else 
                    echo "${full_python_version}, ${full_numpy_version}: Failed" >> testing_pip_clawpack.log
                fi
            done
        done
