name: Test Clawpack CI

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

  workflow_dispatch:

permissions:
  contents: read

env:
  CLAW: ${{ github.workspace }}

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Set up Python 3.8.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.8.9"
    - name: Install dependencies
      run: |
        # sudo apt-get update
        # sudo apt-get install gfortran
        brew update
        #Force gfortran reinstallation
        brew reinstall gfortran      

        python -m pip install --upgrade pip
        pip install flake8 meson-python ninja pytest numpy
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install clawpack
      run: |
        pip install clawpack
